name: Run Tests with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Optional: clean npm cache if you've had weird install issues
    - name: Clean npm cache (optional)
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install

    # Make sure react-scripts (and others) are executable
    - name: Fix permissions (optional but helpful on Linux)
      run: chmod +x ./node_modules/.bin/*

    - name: Run tests with coverage
      run: npm run test:coverage || true


